FROM php:7.1.26-stretch
ENV DEBIAN_FRONTEND="noninteractive"
RUN echo 'deb http://ftp.debian.org/debian stretch-backports main' > /etc/apt/sources.list.d/stretch-backports.list
RUN apt-get update -yqq && apt-get upgrade -yqq
RUN apt-get install -yqq --no-install-recommends -t stretch-backports librdkafka-dev
RUN apt-get install wget unzip gzip zlib1g-dev git -yqq
RUN docker-php-ext-install zip pdo_mysql
RUN wget https://raw.githubusercontent.com/composer/getcomposer.org/76a7060ccb93902cd7576b67264ad91c8a2700e2/web/installer -O - -q | php -- --quiet && mv composer.phar /usr/local/bin/composer
RUN pecl update-channels && pecl install rdkafka-3.1.0 apcu && docker-php-ext-enable rdkafka apcu

# OPCACHE
RUN docker-php-ext-install opcache

# XDEBUG
RUN wget http://xdebug.org/files/xdebug-2.6.0.tgz
RUN tar -xvzf xdebug-2.6.0.tgz
RUN cd xdebug-2.6.0 && phpize && ./configure && make
RUN cp xdebug-2.6.0/modules/xdebug.so /usr/local/lib/php/extensions/no-debug-non-zts-20160303
RUN echo 'zend_extension = /usr/local/lib/php/extensions/no-debug-non-zts-20160303/xdebug.so' > /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN docker-php-ext-enable xdebug

COPY opcache_jenkins.ini $PHP_INI_DIR/conf.d/opcache_jenkins.ini
